#!/bin/sh

SPARK_MASTER=${SPARK_MASTER:-1g}
DRIVER_MEMORY=${SPARK_DRIVER_MEMORY:-1g}
EXECUTOR_MEMORY=${SPARK_EXECUTOR_MEMORY:-1g}

exec spark-submit --master SPARK_MASTER --driver-memory DRIVER_MEMORY --executor-memory EXECUTOR_MEMORY $USPTO_PARSER_JAR_PATH "$@"